app:
  file:
    max-size: 5242880 # 5МБ
    allowed-extensions: xls, xlsx

server:
  port: 8081
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: passworDarito
    key-store-type: PKCS12
    key-alias: firestarter

spring:
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      upload: "upload-topic"
      status: "status-topic"

  data:
    mongodb:
      host: localhost
      port: 27017
      database: firestarter_db

  cloud:
    config:
      uri: http://localhost:8888
      profile: local

  servlet:
    multipart:
      max-file-size: 10MB    # Максимальный размер одного файла
      max-request-size: 10MB # Максимальный размер всего запроса

logging:
  level:
    org.springframework.kafka: DEBUG