server:
  port: 8083

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: file-status-processor-group
      auto-offset-reset: earliest
    topics:
      status: "status-topic"

  data:
    mongodb:
      host: localhost
      port: 27017
      database: firestarter_db

logging:
  level:
    org.springframework.kafka: DEBUG